site_name: Fateful
repo_url: https://github.com/jerkos/fateful
repo_name: fateful
theme:
  #features:
  #  - navigation.tabs
  # - navigation.tabs.sticky
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - mkdocstrings:

nav:
  - ğŸ”¥ Getting started: index.md
  - ğŸ’¼ Containers:
    - â“ Option monad: containers/option.md
    - âš™ï¸ Result monad: containers/result.md
    - ğŸš€ Async try: containers/async-try.md
  - Useful functions: func.md
  - Http helpers: http.md
  - Container: container.md
  - Json helpers: json.md

